// Generator for src/tables/spirv_opcodes.c — run by hand when vendor/spirv.h is
// updated; the output is checked in (the library has no build-time codegen).
//
//   cc -O2 tools/gen_spirv_opcodes.c -o /tmp/gen_opcodes
//   /tmp/gen_opcodes vendor/spirv.h > src/tables/spirv_opcodes.c
//
// It reads the vendored header's own SpvOpToString table (the authoritative
// opcode→mnemonic list), then searches for an FNV-1a seed whose 16-bit fold is
// collision-free across every mnemonic. The emitted table stores that 16-bit
// hash and the 16-bit opcode — no strings — so lookup costs no .rodata beyond a
// flat {u16,u16} array. SPIR-V opcodes are 16-bit by definition (the opcode is
// the low half of an instruction word), so the value always fits.

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>

static uint16_t h16(const char *s, int len, uint32_t seed) {
	uint32_t h = seed;
	for (int i = 0; i < len; i++) h = (h ^ (uint8_t)s[i]) * 16777619u;
	return (uint16_t)((h ^ (h >> 16)) & 0xFFFFu);
}

int main(int argc, char **argv) {
	const char *path = argc > 1 ? argv[1] : "vendor/spirv.h";
	FILE *f = fopen(path, "rb");
	if (!f) { fprintf(stderr, "cannot open %s\n", path); return 1; }

	// collect mnemonics from lines like:  case SpvOpFAdd: return "OpFAdd";
	// (the longest real mnemonics are ~66 chars — INTEL/KHR extension ops)
	static char names[4096][96];
	int  n = 0;
	char line[512];
	while (n < 4096 && fgets(line, sizeof(line), f)) {
		if (!strstr(line, "case SpvOp")) continue;
		char *q = strstr(line, "return \"Op");
		if (!q) continue;
		q += strlen("return \"");
		char *end = strchr(q, '"');
		if (!end) continue;
		int len = (int)(end - q);
		if (len <= 0 || len >= 96) continue;
		memcpy(names[n], q, (size_t)len);
		names[n][len] = '\0';
		// defensive dedup (a repeated mnemonic can never be made collision-free)
		int dup = 0;
		for (int i = 0; i < n; i++) if (strcmp(names[i], names[n]) == 0) { dup = 1; break; }
		if (!dup) n++;
	}
	fclose(f);
	if (n == 0) { fprintf(stderr, "no opcodes found in %s\n", path); return 1; }

	// search a seed whose 16-bit fold has no collisions over the whole set
	static uint8_t seen[65536];
	uint32_t seed = 0;
	int      found = 0;
	for (uint32_t s = 2166136261u; s != 2166136261u + 8000000u; s++) {
		memset(seen, 0, sizeof(seen));
		int ok = 1;
		for (int i = 0; i < n; i++) {
			uint16_t hv = h16(names[i], (int)strlen(names[i]), s);
			if (seen[hv]) { ok = 0; break; }
			seen[hv] = 1;
		}
		if (ok) { seed = s; found = 1; break; }
	}
	if (!found) { fprintf(stderr, "no collision-free 16-bit seed for %d opcodes\n", n); return 1; }
	fprintf(stderr, "seed 0x%08x is collision-free over %d opcodes\n", seed, n);

	printf(
	"// GENERATED by tools/gen_spirv_opcodes.c — do not edit by hand.\n"
	"// Maps a SPIR-V opcode mnemonic (\"OpFAdd\") to its SpvOp value, for spirv_asm\n"
	"// blocks. To keep the binary small we store a 16-bit hash of each mnemonic\n"
	"// rather than the string: OPCODE_HASH_SEED was searched so the fold collides\n"
	"// for no two opcodes (they are 16-bit, so the value fits a u16 too). Trade-off:\n"
	"// an unknown mnemonic that happens to hash to a real one resolves to that\n"
	"// opcode instead of -1 — spirv-val is the backstop. Regenerate: see the tool.\n"
	"\n"
	"#include \"spirv_opcodes.h\"\n"
	"\n"
	"#include \"../../vendor/spirv.h\"\n"
	"\n"
	"#define OPCODE_HASH_SEED %uu\n"
	"\n"
	"typedef struct opcode_row_t {\n"
	"\tuint16_t hash;\n"
	"\tuint16_t op;\n"
	"} opcode_row_t;\n"
	"\n"
	"static const opcode_row_t opcode_table[] = {\n", seed);

	for (int i = 0; i < n; i++)
		printf("\t{ 0x%04x, Spv%s },\n", h16(names[i], (int)strlen(names[i]), seed), names[i]);

	printf(
	"};\n"
	"\n"
	"static uint16_t opcode_hash(svsl_str_t s) {\n"
	"\tuint32_t h = OPCODE_HASH_SEED;\n"
	"\tfor (int32_t i = 0; i < s.len; i++) h = (h ^ (uint8_t)s.ptr[i]) * 16777619u;\n"
	"\treturn (uint16_t)((h ^ (h >> 16)) & 0xFFFFu);\n"
	"}\n"
	"\n"
	"int32_t svsl_spirv_opcode_lookup(svsl_str_t name) {\n"
	"\tuint16_t want = opcode_hash(name);\n"
	"\tfor (int32_t i = 0; i < (int32_t)(sizeof(opcode_table) / sizeof(opcode_table[0])); i++)\n"
	"\t\tif (opcode_table[i].hash == want) return opcode_table[i].op;\n"
	"\treturn -1;\n"
	"}\n");
	return 0;
}
